version: 1.0.{build}
assembly_info:
  patch: false
configuration: Release
install:
  - choco install gitversion.portable -pre -y
before_build:
  - cmd: nuget restore
  - ps: gitversion /l console /output buildserver /updateassemblyinfo 
build:
  verbosity: minimal
after_build:
  - cmd: ECHO nuget pack NServiceBus.SequenceGate\NServiceBus.SeqeuenceGate.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack NServiceBus.SequenceGate\NServiceBus.SeqeuenceGate.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "NServiceBus.SequenceGate.%GitVersion_NuGetVersion%.nupkg"
before_test:
  - cmd: sqlcmd -S localhost,1433 -U sa -P Password12! -Q "CREATE DATABASE Acceptance" -d "master"
  - cmd: sqlcmd -S localhost,1433 -U sa -P Password12! -i "%APPVEYOR_BUILD_FOLDER%\NServiceBus.SequenceGate\create.sql" -d "Acceptance"
test:
  assemblies:
  - 'NServiceBus.SequenceGate.Tests.Unit.dll'
  - 'NServiceBus.SequenceGate.Tests.Acceptance.dll'
services:
  - mssql2014
  - msmq