version: 1.0.{build}
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
before_test:
- cmd: sqlcmd -S localhost,1433 -U sa -P Password12! -Q "CREATE DATABASE Acceptance" -d "master"
- cmd: sqlcmd -S ".\SQL2012SP1" -U sa -P Password12! -i "%APPVEYOR_BUILD_FOLDER%\NServiceBus.SequenceGate\create.sql" 
test:
  assemblies:
  - 'NServiceBus.SequenceGate.Tests.Unit.dll'
  - 'NServiceBus.SequenceGate.Tests.Acceptance.dll'
services:
  - mssql2014
  - msmq